### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by ZI-Youtuber**
@xItzDiamondx  Just to check if I did the code the right way

I added the code that you put in the chat to replace `width="1920" height="1080" ` 

The code that you put in the team chat was:

```
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
```
The code was originally: 

`<iframe src="https://scratch.mit.edu/projects/16586232/embed" allowtransparency="true" width="1920" height="1080" frameborder="0" scrolling="no" allowfullscreen></iframe>`

### CODE REVIEW

**Comment by xItzDiamondx** [comment]
It was oversize on my laptop screen. Here is the width + height: 1518 x 853

**Comment by xItzDiamondx** [comment]
I'll merge it for now because it doesn't have any conflicts.

**Comment by xItzDiamondx** [comment]
Once merged, this is the output.
Screenshot 2021-04-16 12 15 52 PM

**Comment by xItzDiamondx** [comment]
I believe we can center it and then that will be good.

**Comment by ZI-Youtuber** [comment]
@xItzDiamondx Yeah it looks the right size 

But It has to be adjustable depending on the screen size

**Pull request merged**
